### ISSUE TITLE
Can it be tailored to be used in streamlit?

### ISSUE THREAD

**Issue by chihpoc** [medialab/ipysigma#205]
Also, it shows the text `Sigma(nx.Graph with 74 nodes and 248 edges)` in Jupyter notebook. How can we tell Jupyter to show the graph viz instead?

**Comment by Yomguithereal** [comment]
Hello @chihpoc, I know next to nothing about streamlit so I really have no clue about this. I read [here](https://discuss.streamlit.io/t/ipywidgets-wip/3870/14) that there is not yet support for `ipywidgets`, but you might want to try the idea at the end of the thread by doing this:

```python
from ipywidgets import embed
snippet = embed.embed_snippet(views=Sigma(...))
html = embed.html_template.format(title="", snippet=snippet)

import streamlit.components.v1 as components
components.html(html, width=view_width, height=view_height)
``` 

> Also, it shows the text Sigma(nx.Graph with 74 nodes and 248 edges) in Jupyter notebook.

In your notebook, when developing or when reading it while rendered to static html such as nbviewer or GitHub? Regarding the first case, this looks like you have a problem regarding notebook extensions that you might want to debug using the `jupyter nbextension list` and try reinstalling, upgrading jupyter and rebooting kernels and stuff. Regarding the second case, that is to be expected unfortunately because those static renderer don't accept arbitrary JavaScript logic for practical and security reasons. In which case you should turn to [Binder](https://mybinder.org/) or render your Sigma widget as html using the dedicated methods.

**Comment by chihpoc** [comment]
The graph vis shows up in Jupyter after reinstalling `ipywidgets` & `widgetsnbextension`. Thanks a lot!

```
pip uninstall ipywidgets widgetsnbextension
pip install ipywidgets
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```
