### ISSUE TITLE
Update the graph data and trigger redraw

### ISSUE THREAD

**Issue by chihpoc** [medialab/ipysigma#206]
Is it possible to update the graph data of an existing Sigma widget and trigger auto-refresh? It'd be a very useful feature when we try to pair ipysigma widgets with ipywidgets to filter the graph interactively.

**Comment by Yomguithereal** [comment]
Hello @chihpoc, we could try something in this vein yes, but it's far from trivial to implement and there are multiple cases to envision. For instance, scales for each of the visual variables have to be recomputed, or not. What about adding nodes/adding edges or removing them etc. If you just want to filter, I think it simplifies things because it is just a matter of hiding/showing things. Could you describe your precise use-case please?

**Comment by chihpoc** [comment]
Thanks a lot for your prompt and detailed response @Yomguithereal! Yes it can be very complicated. I will use `clear_output` for now.
